### ISSUE TITLE
Tidal-dl Termux Android @yaronzz

### ISSUE THREAD

**Issue by dk2641** [yaronzz/yaronzz.github.io#1]
Tidal Media Downloader Termux Android Not Working It Shows Some Error Message Like This 👇 Please Fix The Issue As Soon As Possible 🙏
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connection.py", line 361, in connect
    self.sock = ssl_wrap_socket(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connection.py", line 361, in connect
    self.sock = ssl_wrap_socket(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/tidal-dl", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/tidal_dl/__init__.py", line 199, in main
    if logIn(cf.username, cf.password) == False:
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/tidal_dl/__init__.py", line 44, in logIn
    account3 = TidalMobileSession(username, password, TIDAL_TOKEN.clientID, cf)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/tidal_dl/session.py", line 46, in __init__
    if self.valid():
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/tidal_dl/session.py", line 129, in valid
    r = requests.get('https://api.tidal.com/v1/sessions', headers=self.auth_headers())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by yuttanahindang** [comment]
Why am I loading quality files?24bit Not even though the album that I chose was Master Already
